repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
      exclude: pydhcplib
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
      args: ["--ignore=W503,E203", "--show-source", --max-line-length=88]
      exclude: (pydhcplib|example)
    - id: check-json
    - id: check-yaml
    - id: pretty-format-json
      args: [--autofix, --top-keys=_default_]
    - id: detect-private-key
    - id: check-added-large-files

